### ISSUE TITLE
Drop Node 4 support

### ISSUE THREAD

**Issue by malept** [electron-userland/electron-packager#815]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

[Node 4 LTS is scheduled to be EOL'd on 2018-04-30](https://github.com/nodejs/Release/blob/643af71ee8365efbdccaa134690425ea05931279/README.md#release-schedule). With that, Electron Packager will also drop Node 4 support and start using Node features introduced in Node 5 and 6.

## TODO

* [x] Drop from Travis & AppVeyor
* [x] Update `engines` in `package.json`
* [x] [destructured assignments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), including `require` calls (e.g., `const { bar } = require('foo')` instead of `const bar = require('foo').bar`)
* [x] [`Array.prototype.includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)
* [ ] [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters)
* [x] Upgrade `plist` to >= 3.0 (which also drops Node 4 support)
* [x] `cli.js` will stay the way it is, except noting that the minimum Node version is 6 instead of 4.
